config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :burgers
  root 'burgers#index'
  # root 'registrations#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burger.rb
class Burger < ApplicationRecord
    belongs_to :user, required: false
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :burgers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:burger_level])
    end
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def burger_params
      params.require(:burger).permit(:name, :drool, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_with(model: burger, local: true) do |form| %>
  <% if burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% burger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :drool_worthiness %>
    <%= form.select :drool, ["", 10, 9 , 8, 7, 6, 5, 4, 3, 2, 1] %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing Burger</h1>

<%= render 'form', burger: @burger %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Burgers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Drool</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @burgers.each do |burger| %>
      <tr>
        <td><%= burger.name %></td>

        <td><%= burger.drool %></td>
        
        <td><%= burger.description %></td>
        <td><%= link_to 'Show', burger %></td>
        <td><%= link_to 'Edit', edit_burger_path(burger) %></td>
        <td><%= link_to 'Destroy', burger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Burger', new_burger_path %>

app/views/burgers/new.html.erb
<h1>New Burger</h1>

<%= render 'form', burger: @burger %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @burger.name %>
</p>

<p>
  <strong>Drool:</strong>
  <%= @burger.drool %>
</p>

<p>
  <strong>Description:</strong>
  <%= @burger.description %>
</p>

<%= link_to 'Edit', edit_burger_path(@burger) %> |
<%= link_to 'Back', burgers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Burgergram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <% if user_signed_in? %>
        <%= link_to('HOME', root_path) %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= link_to('HOME', root_path) %>
        <%= link_to('LOGIN', new_user_session_path)  %>
        <%= link_to('SIGN UP', new_user_registration_path) %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>